[workspace]

[package]
name = "raytrace"
version = "0.1.0"
authors = ["Code_Cube <therealcodecube@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.14"
vulkano-shaders = "0.14"
vulkano-win = "0.14"
cgmath = "0.17"
image = "0.22"
winit = "0.19"
time = "0.1.42"
noise = "0.6.0"
rand = "0.7.2"
array-macro = "1.0.4"
crend = { path = "crend" }
shaders = { path = "shaders" }