[package]
name = "crend"
version = "0.1.0"
authors = ["Code_Cube <therealcodecube@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
libc="0.2"

[dependencies.glfw]
version="0.34"
features=["vulkan"]